version: "2"

services:
  matomo:
    container_name: matomo
    image: matomo
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - VIRTUAL_HOST=matomo.example.com
    env_file:
      - ./db.env
    networks:
      - proxy
      - matnet
    depends_on:
      - matomo_db
    restart: unless-stopped

  matomo_db:
    container_name: matomo_db
    image: mariadb
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=inventa
    env_file:
      - ./db.env
    networks:
      - net
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
  matnet:
    driver: bridge
