version: "2"

services:
  matomo:
    container_name: matomo
    image: matomo
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - VIRTUAL_HOST=matomo.example.com
    env_file:
      - ./db.env
    volumes:
      - /home/xxxx/config/matomo/web:/var/www/html
    networks:
      - proxy
      - matnet
    depends_on:
      - matomo_db
    restart: unless-stopped

  matomo_db:
    container_name: matomo_db
    image: mariadb
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=inventa
    volumes:
      - /home/xxxx/config/matomo/db:/var/lib/mysql
    env_file:
      - ./db.env
    networks:
      - matnet
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true
  matnet:
    driver: bridge
